// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKmsjoWTQS7rk-56HaWQ9FI7KYMocoCKU',
    appId: '1:884184513529:web:46707c8332034373995b28',
    messagingSenderId: '884184513529',
    projectId: 'minicrm-8575d',
    authDomain: 'minicrm-8575d.firebaseapp.com',
    storageBucket: 'minicrm-8575d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjVPl1vneMq-KO2selNvn0Ecg318sukZw',
    appId: '1:884184513529:android:54066778be973917995b28',
    messagingSenderId: '884184513529',
    projectId: 'minicrm-8575d',
    storageBucket: 'minicrm-8575d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-0HCeMWGmBndG1-zrkXFTmElShQuHxKE',
    appId: '1:884184513529:ios:267ce2465c45dea6995b28',
    messagingSenderId: '884184513529',
    projectId: 'minicrm-8575d',
    storageBucket: 'minicrm-8575d.firebasestorage.app',
    iosBundleId: 'com.srisoftwarez.leadcapture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-0HCeMWGmBndG1-zrkXFTmElShQuHxKE',
    appId: '1:884184513529:ios:2ca4f423ce3d10cf995b28',
    messagingSenderId: '884184513529',
    projectId: 'minicrm-8575d',
    storageBucket: 'minicrm-8575d.firebasestorage.app',
    iosBundleId: 'com.srisoftwarez.leadcapture.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKmsjoWTQS7rk-56HaWQ9FI7KYMocoCKU',
    appId: '1:884184513529:web:4c6b449427e46eaa995b28',
    messagingSenderId: '884184513529',
    projectId: 'minicrm-8575d',
    authDomain: 'minicrm-8575d.firebaseapp.com',
    storageBucket: 'minicrm-8575d.firebasestorage.app',
  );
}
